### ISSUE TITLE
wrong detection for some mice

### ISSUE THREAD

**Issue by mattia-b89** [ian-kelling/evhz#3]
Hi, I know I'm opening an issue with too few info, but at the moment is the only thing I can do.
Briefly, seems that evhz doesn't detect the correct value, at least with me
https://bbs.archlinux.org/viewtopic.php?id=187904

**Comment by Nek80** [comment]
I have the same problem with mattla-b89, it works up to 500hz but not 1000hz. This problem occurs with a Zowie FK2 mouse (correctly setup at 1000hz and confirmed in Windows 7) and a Razer DeathAdder 3.5G. The only mouse that works and gets reported by evhz correctly at 1000hz is my SteelSeries Sensei Raw.

Can you help out to find what's wrong?

**Comment by Nek80** [comment]
I just tried dimr.exe through WINE and it reports 1000hz. So in reality the mouse and the kernel runs in 1000hz correctly and this is a bug with the reporting of evhz.

**Comment by ian-kelling** [comment]
I didn't have much to go on before and this dropped off the priority list. I have a razer naga mouse I can try to reproduce this with. If it doesn't repro, I'll get one of those mice you mentioned and try to figure it out. Do you prefer the zowie or the razer?

**Comment by Nek80** [comment]
I prefer the Zowie. Thanks.

**Comment by maxis123** [comment]
also maybe its not evhz bug. on 12.04 every one of three of my mices (all are 1000hz hardware default without needing drivers devices) worked at 1000hz polling verified by evhz itself. 

currently on 14.10 evhz reports max 500hz for every one of them (using system mousepoll settings they can go 250,125, but not 1000hz) 

just thought to inform you about this 

regards

**Comment by Nek80** [comment]
I found the problem. It has nothing to do with evhz. It's a bug in the kernel: https://bugzilla.kernel.org/show_bug.cgi?id=60586

A workaround is to use USB ports that have the ehci-pci driver, those work with 1000hz polling rate correctly. Those with uhci_hcd don't, they only go up to 500hz causing jittering and microstuttering movement.

**Comment by mattia-b89** [comment]
perfect.....at least now we know which is the problem!
thank you @Nek80

**Comment by ian-kelling** [comment]
Thank you @Nek80. This is a bit late, but I've confirmed that a Zowie FK2 gets 1000hz on my machine. I've updated the readme with the kernel bug link and am closing this issue.
